### ISSUE TITLE
Length of motion used for calculating evaluation metrics

### ISSUE THREAD

**Issue by sohananisetty** [Stanford-TML/EDGE#12]
Your paper mentioned: "We compute these metrics on 5-second dance clips produced by each approach". However, in the codebase, you are generating 30s clips by default. Can you please clarify how you computed the metrics comparing other methods to yours?

**Comment by jtseng20** [comment]
The 30 second clips are just the default setting used for visualizing demo purposes in this repo, the procedure cited in the paper is correct.
