### ISSUE TITLE
How to synchronize with sound

### ISSUE THREAD

**Issue by ryhhtn** [Stanford-TML/EDGE#21]
Thanks for sharing the interesting code.

I immediately tried test.py.
The result was about 150 seconds of input and 30 seconds of output (*.mp4).
Is it possible to synchronize the input and output and check the dance to the sound for this result?

https://github.com/Stanford-TML/EDGE/assets/18476440/2dd7a6c6-a4db-4fc0-a419-6185c235d5bc

**Comment by ryhhtn** [comment]
I'm so sorry.
I was mistaken.

**Comment by dongxinghua** [comment]
How to synchronize with sound?  the result .fbx without music !

**Comment by dongxinghua** [comment]
how to produce mp4 file with sound?   I only get the .fbx without sound.
